### ISSUE TITLE
Doesn't seem to work with thumbnail images rather than links.

### ISSUE THREAD

**Issue by andywarren** [iamvery/galleriffic#1]
I've searched hi and low for the solution that you provide in your example-6.html file, and finally stumbled across this git fork of galleriffic.  I am using the thumbnail layout for galleriffic and this does not seem to work for it.  When I click the main image in galleriffic it just cycles to the next in the gallery.  What can I do to make this work with the thumbnail galleriffic gallery?  Thanks!

**Comment by iamvery** [comment]
@andywarren,

This plugin adds a couple extra options to the `galleriffic` method.

```
// makes the "click" functionality of images open in a fancybox rather than advance to the next
enableFancybox: true

// a hash of options to be sent to the fancybox that is created
fancyOptions: { 'titlePosition' : 'outside', 'overlayColor' : '#000', 'overlayOpacity' : 0.8 }
```

So an example gallery with fancybox support may look something like

```
$('#thumbs').galleriffic({
  // other galleriffic options ...
  enableFancybox: true,
  fancyOptions: { 'titlePosition' : 'outside', 'overlayColor' : '#000', 'overlayOpacity' : 0.8 }
});
```

Maybe this will point you in the right direction!
