### ISSUE TITLE
Default image

### ISSUE THREAD

**Issue by aganglada** [iamvery/galleriffic#3]
Hello!

Is there any option to set a default image in the background to put in the gallery while the current image is loading? like in here:

https://www.airbnb.es/

as you see there is a grey image in the background.

Thanks in advantage :)

**Comment by iamvery** [comment]
@aganglada I hate to leave you hanging without a response! I don't do anything to maintain this repo, and it has been awhile since I've used the code. Have you attempted anything to make this work?

Also, sorry it took me awhile to reply, I wasn't even watching the repo myself :flushed:

**Comment by aganglada** [comment]
Well I simply set a image in the background of the gallery, so that stay there always and prevent the blinking :) Don't worry man

**Comment by iamvery** [comment]
:+1:

**Comment by aganglada** [comment]
One more question... Do you know who is the real maintainer? Thanks in advantage!

**Comment by iamvery** [comment]
All I know is https://github.com/iamvery/galleriffic/commit/c6c36b6be4bea18f44e753b5c56eb80118d975bc#diff-04c6e90faac2675aa89e2176d2eec7d8R4 (http://www.twospy.com/galleriffic) which hasn't been updated in years `¯\_(ツ)_/¯`
