### ISSUE TITLE
WordPress version

### ISSUE THREAD

**Issue by ghost** [iamvery/galleriffic#4]
Hi Jay. Just letting you know that I've added this to a version of my WordPress plugin of Galleriffic. Thanks for the good work! I had a lot of requests for this. See here http://thriveweb.com.au/the-lab/wordpress-gallery-plugin-photospace-2/

**Comment by iamvery** [comment]
Don't credit me, I just created a GH repo. Glad you found it useful :+1:

**Comment by thriveweb** [comment]
You added fancybox didn't you?

**Comment by iamvery** [comment]
Yeah, I suppose I did. It's been a long time, and I'm not very proud of my JavaScripting :laughing:
