### ISSUE TITLE
I found bug mannnn

### ISSUE THREAD

**Issue by sonylifull** [iamvery/galleriffic#5]
I found bug, if we do multiple click on the images then sometimes it will shows like below.

![bug](https://cloud.githubusercontent.com/assets/11550101/10392632/f2f7ed88-6eb2-11e5-9336-1ea0c692f837.png)

**Comment by iamvery** [comment]
I've seen this before as well. I'm not the original creator the library, and I don't have a strong motivation to spend time fixing these things. However I'm always open to a PR if you feel so obliged.

(yes I just noticed that there is an open PR from 2013 :flushed:, embarrassing)

**Comment by sonyarianto** [comment]
Hahahah ok ok :)
