### ISSUE TITLE
Ability to hide the Page ID if there is only 1 page

### ISSUE THREAD

**Issue by elliottmangham** [iamvery/galleriffic#7]
Hi,
I'd love the ability or to know how to hide the page ID if there's only one page on the gallery?

See: http://stackoverflow.com/questions/37139949/hide-page-number-if-theres-only-one-page-gallery-on-galleriffic-js

Kind regards

**Comment by iamvery** [comment]
Hi @elliottmangham! As you can see in [the readme](https://github.com/iamvery/galleriffic#galleriffic---a-jquery-photo-gallery--slideshow-plugin), I am not the creator of this library. I just added it to Github to manage some parts of it for myself. I'm afraid I don't have any interest at this time to maintain the code. Feel free to send a PR along if you have a change, though it may take some time to get attention.
